<?php
$dalTableepisodeview = array();
$dalTableepisodeview["idEpisode"] = array("type"=>3,"varname"=>"idEpisode");
$dalTableepisodeview["idFile"] = array("type"=>3,"varname"=>"idFile");
$dalTableepisodeview["c00"] = array("type"=>201,"varname"=>"c00");
$dalTableepisodeview["c01"] = array("type"=>201,"varname"=>"c01");
$dalTableepisodeview["c02"] = array("type"=>201,"varname"=>"c02");
$dalTableepisodeview["c03"] = array("type"=>201,"varname"=>"c03");
$dalTableepisodeview["c04"] = array("type"=>201,"varname"=>"c04");
$dalTableepisodeview["c05"] = array("type"=>201,"varname"=>"c05");
$dalTableepisodeview["c06"] = array("type"=>201,"varname"=>"c06");
$dalTableepisodeview["c07"] = array("type"=>201,"varname"=>"c07");
$dalTableepisodeview["c08"] = array("type"=>201,"varname"=>"c08");
$dalTableepisodeview["c09"] = array("type"=>201,"varname"=>"c09");
$dalTableepisodeview["c10"] = array("type"=>201,"varname"=>"c10");
$dalTableepisodeview["c11"] = array("type"=>201,"varname"=>"c11");
$dalTableepisodeview["c12"] = array("type"=>200,"varname"=>"c12");
$dalTableepisodeview["c13"] = array("type"=>200,"varname"=>"c13");
$dalTableepisodeview["c14"] = array("type"=>201,"varname"=>"c14");
$dalTableepisodeview["c15"] = array("type"=>201,"varname"=>"c15");
$dalTableepisodeview["c16"] = array("type"=>201,"varname"=>"c16");
$dalTableepisodeview["c17"] = array("type"=>200,"varname"=>"c17");
$dalTableepisodeview["c18"] = array("type"=>201,"varname"=>"c18");
$dalTableepisodeview["c19"] = array("type"=>201,"varname"=>"c19");
$dalTableepisodeview["c20"] = array("type"=>201,"varname"=>"c20");
$dalTableepisodeview["c21"] = array("type"=>201,"varname"=>"c21");
$dalTableepisodeview["c22"] = array("type"=>201,"varname"=>"c22");
$dalTableepisodeview["c23"] = array("type"=>201,"varname"=>"c23");
$dalTableepisodeview["idShow"] = array("type"=>3,"varname"=>"idShow");
$dalTableepisodeview["strFileName"] = array("type"=>201,"varname"=>"strFileName");
$dalTableepisodeview["strPath"] = array("type"=>201,"varname"=>"strPath");
$dalTableepisodeview["playCount"] = array("type"=>3,"varname"=>"playCount");
$dalTableepisodeview["lastPlayed"] = array("type"=>201,"varname"=>"lastPlayed");
$dalTableepisodeview["dateAdded"] = array("type"=>201,"varname"=>"dateAdded");
$dalTableepisodeview["strTitle"] = array("type"=>201,"varname"=>"strTitle");
$dalTableepisodeview["strStudio"] = array("type"=>201,"varname"=>"strStudio");
$dalTableepisodeview["premiered"] = array("type"=>201,"varname"=>"premiered");
$dalTableepisodeview["mpaa"] = array("type"=>201,"varname"=>"mpaa");
$dalTableepisodeview["resumeTimeInSeconds"] = array("type"=>5,"varname"=>"resumeTimeInSeconds");
$dalTableepisodeview["totalTimeInSeconds"] = array("type"=>5,"varname"=>"totalTimeInSeconds");
$dalTableepisodeview["idSeason"] = array("type"=>3,"varname"=>"idSeason");
$dal_info["episodeview"]=&$dalTableepisodeview;

?>